/**
 * Mock Data Generator for UI Testing
 * 
 * Provides realistic test data matching the backend API structure
 * so we can test the UI without a running backend.
 * 
 * To use: Import and inject into composables or replace API calls in dev mode
 */

export const generateMockCompanies = () => [
  {
    id: 1,
    name: 'Techstart GmbH',
    summary: 'Software development company focused on web technologies',
    url: 'https://techstart.de',
    urlJobs: 'https://techstart.de/jobs',
    jobCount: 3,
    addresses: [
      {
        id: 101,
        street: 'Mainzer Straße',
        number: '42',
        postcode: '10115',
        city: 'Berlin',
        country: 'Deutschland',
        distance: 2.5,
      },
      {
        id: 102,
        street: 'Königstraße',
        number: '10',
        postcode: '70173',
        city: 'Stuttgart',
        country: 'Deutschland',
        distance: 15.8,
      },
    ],
    telPerson: 'Max Müller',
    tel: '+49 30 123456',
    mailPerson: 'contact@techstart.de',
    mail: 'hr@techstart.de',
  },
  {
    id: 2,
    name: 'InnovateLabs AG',
    summary: 'Innovation hub for AI and machine learning solutions',
    url: 'https://innovatelabs.de',
    urlJobs: 'https://innovatelabs.de/career',
    jobCount: 2,
    addresses: [
      {
        id: 201,
        street: 'Technologiering',
        number: '5',
        postcode: '03046',
        city: 'Cottbus',
        country: 'Deutschland',
        distance: 8.3,
      },
    ],
    telPerson: 'Dr. Sarah Schmidt',
    tel: '+49 355 789012',
    mailPerson: 'Dr. Sarah Schmidt',
    mail: 'sarah.schmidt@innovatelabs.de',
  },
  {
    id: 3,
    name: 'Digital Solutions AG',
    summary: 'Enterprise consulting and digital transformation',
    url: 'https://digital-solutions.de',
    urlJobs: null,
    jobCount: 1,
    addresses: [
      {
        id: 301,
        street: 'Am Waldrand',
        number: '1-3',
        postcode: '82140',
        city: 'Dachau',
        country: 'Deutschland',
        distance: 35.2,
      },
    ],
    telPerson: 'Christian Weber',
    tel: '+49 8131 5678',
    mailPerson: 'Christian Weber',
    mail: 'christian.weber@digital-solutions.de',
  },
];

export const generateMockJobsForCompany = (companyId) => {
  const jobsByCompany = {
    1: [
      {
        id: 1001,
        companyId: 1,
        addressId: 101,
        source: 'Frontend Developer (Vue.js)',
        status: 'OPEN',
        features: 'Vue.js, TypeScript, REST APIs',
        text: 'Wir suchen einen erfahrenen Frontend-Entwickler mit Schwerpunkt auf Vue.js 3 und moderner Web-Entwicklung. Du wirst in einem agilen Team an spannenden Projekten arbeiten.',
        found: new Date('2024-01-15'),
        url: 'https://techstart.de/jobs/1001',
        street: 'Mainzer Straße',
        number: '42',
        postcode: '10115',
        city: 'Berlin',
        country: 'Deutschland',
        distance: 2.5,
        telPerson: 'Anna Klein',
        tel: '+49 30 123456-10',
        mailPerson: 'Anna Klein',
        mail: 'anna.klein@techstart.de',
        teilzeit: 'Nein',
        homeoffice: '3 Tage pro Woche',
        gleitzeit: 'Flexible Arbeitszeiten',
        communicationCount: 3,
      },
      {
        id: 1002,
        companyId: 1,
        addressId: 101,
        source: 'Backend Developer (Node.js)',
        status: 'IN_PROGRESS',
        features: 'Node.js, Express, PostgreSQL, Docker',
        text: 'Entwickle scalable Backend-Systeme mit Node.js und Express. Trage zu modernen Architektur-Entscheidungen bei.',
        found: new Date('2024-01-20'),
        url: 'https://techstart.de/jobs/1002',
        street: 'Mainzer Straße',
        number: '42',
        postcode: '10115',
        city: 'Berlin',
        country: 'Deutschland',
        distance: 2.5,
        telPerson: 'Michael Schmidt',
        tel: '+49 30 123456-20',
        mailPerson: 'Michael Schmidt',
        mail: 'michael.schmidt@techstart.de',
        teilzeit: 'Nein',
        homeoffice: 'Vollständig Remote',
        gleitzeit: 'Flexible Arbeitszeiten',
        communicationCount: 1,
      },
      {
        id: 1003,
        companyId: 1,
        addressId: 102,
        source: 'DevOps Engineer',
        status: 'CLOSED',
        features: 'Docker, Kubernetes, CI/CD, AWS',
        text: 'Optimiere unsere DevOps-Prozesse und Cloud-Infrastruktur. Bringe deine AWS-Expertise mit.',
        found: new Date('2024-01-10'),
        url: 'https://techstart.de/jobs/1003',
        street: 'Königstraße',
        number: '10',
        postcode: '70173',
        city: 'Stuttgart',
        country: 'Deutschland',
        distance: 15.8,
        telPerson: 'Klaus Wagner',
        tel: '+49 711 654321',
        mailPerson: 'Klaus Wagner',
        mail: 'klaus.wagner@techstart.de',
        teilzeit: 'Möglich',
        homeoffice: 'Je nach Vereinbarung',
        gleitzeit: 'Feste Zeiten',
        communicationCount: 0,
      },
    ],
    2: [
      {
        id: 2001,
        companyId: 2,
        addressId: 201,
        source: 'Machine Learning Engineer',
        status: 'OPEN',
        features: 'TensorFlow, Python, Deep Learning',
        text: 'Entwickle state-of-the-art ML-Modelle und träge zum Forschungs-Portfolio bei.',
        found: new Date('2024-01-22'),
        url: 'https://innovatelabs.de/jobs/2001',
        street: 'Technologiering',
        number: '5',
        postcode: '03046',
        city: 'Cottbus',
        country: 'Deutschland',
        distance: 8.3,
        telPerson: 'Dr. Eva Berg',
        tel: '+49 355 789012-10',
        mailPerson: 'Dr. Eva Berg',
        mail: 'eva.berg@innovatelabs.de',
        teilzeit: 'Nein',
        homeoffice: '2 Tage pro Woche',
        gleitzeit: 'Flexible Arbeitszeiten',
        communicationCount: 2,
      },
      {
        id: 2002,
        companyId: 2,
        addressId: 201,
        source: 'Data Scientist',
        status: 'OPEN',
        features: 'Python, Statistics, Data Analysis',
        text: 'Analysiere komplexe Datensätze und entwickle datengetriebene Lösungen.',
        found: new Date('2024-01-18'),
        url: 'https://innovatelabs.de/jobs/2002',
        street: 'Technologiering',
        number: '5',
        postcode: '03046',
        city: 'Cottbus',
        country: 'Deutschland',
        distance: 8.3,
        telPerson: 'Prof. Dr. Thomas König',
        tel: '+49 355 789012-20',
        mailPerson: 'Prof. Dr. Thomas König',
        mail: 'thomas.koenig@innovatelabs.de',
        teilzeit: 'Nein',
        homeoffice: 'Vollständig Remote',
        gleitzeit: 'Flexible Arbeitszeiten',
        communicationCount: 5,
      },
    ],
    3: [
      {
        id: 3001,
        companyId: 3,
        addressId: 301,
        source: 'Business Consultant',
        status: 'OPEN',
        features: 'SAP, Business Strategy, Change Management',
        text: 'Beraten Kunden bei der digitalen Transformation und Prozessoptimierung.',
        found: new Date('2024-01-25'),
        url: 'https://digital-solutions.de/jobs/3001',
        street: 'Am Waldrand',
        number: '1-3',
        postcode: '82140',
        city: 'Dachau',
        country: 'Deutschland',
        distance: 35.2,
        telPerson: 'Petra Hoffmann',
        tel: '+49 8131 5678-10',
        mailPerson: 'Petra Hoffmann',
        mail: 'petra.hoffmann@digital-solutions.de',
        teilzeit: 'Möglich',
        homeoffice: '1-2 Tage pro Woche',
        gleitzeit: 'Je nach Projekt',
        communicationCount: 0,
      },
    ],
  };

  return jobsByCompany[companyId] || [];
};

export const generateMockTimeline = (jobId) => {
  const timelinesByJob = {
    1001: {
      content: [
        {
          id: 't1001-1',
          jobId: 1001,
          type: 'PHONE',
          status: 'COMPLETED',
          date: new Date('2024-01-25T10:30:00'),
          notes: 'Telefonat mit Anna Klein - Anforderungen besprochen, sehr interessiert an unserem Projekt',
          direction: 'INCOMING',
          duration: '15 min',
        },
        {
          id: 't1001-2',
          jobId: 1001,
          type: 'EMAIL',
          status: 'PENDING',
          date: new Date('2024-01-24T14:15:00'),
          notes: 'Email-Anfrage zur Technologie-Stack erhalten. Antwort: Vue.js 3, TypeScript, Composition API werden verwendet.',
          direction: 'INCOMING',
        },
        {
          id: 't1001-3',
          jobId: 1001,
          type: 'EMAIL',
          status: 'COMPLETED',
          date: new Date('2024-01-20T09:00:00'),
          notes: 'Job-Angebot erhalten. Details überprüfen und Fragen sammeln.',
          direction: 'INCOMING',
        },
      ],
      currentPage: 0,
      totalPages: 1,
      last: true,
    },
    1002: {
      content: [
        {
          id: 't1002-1',
          jobId: 1002,
          type: 'EMAIL',
          status: 'COMPLETED',
          date: new Date('2024-01-23T11:45:00'),
          notes: 'Bewerbung eingereicht. CV und Motivationsschreiben attached.',
          direction: 'OUTGOING',
        },
      ],
      currentPage: 0,
      totalPages: 1,
      last: true,
    },
    2001: {
      content: [
        {
          id: 't2001-1',
          jobId: 2001,
          type: 'PHONE',
          status: 'SCHEDULED',
          date: new Date('2024-02-05T14:00:00'),
          notes: 'Interview mit Dr. Eva Berg vereinbart - Vorstellungsgespräch für ML Engineer Position',
          direction: 'OUTGOING',
          duration: '30 min (geplant)',
        },
        {
          id: 't2001-2',
          jobId: 2001,
          type: 'EMAIL',
          status: 'COMPLETED',
          date: new Date('2024-01-26T16:30:00'),
          notes: 'LinkedIn-Nachricht von Dr. Eva Berg - sehr positives Feedback zu unserem Profil',
          direction: 'INCOMING',
        },
      ],
      currentPage: 0,
      totalPages: 1,
      last: true,
    },
  };

  return timelinesByJob[jobId] || { content: [], currentPage: 0, totalPages: 0, last: true };
};

export const generateMockEnums = () => ({
  communicationTypes: [
    { id: 'phone', label: 'Telefon' },
    { id: 'email', label: 'E-Mail' },
    { id: 'interview', label: 'Interview' },
    { id: 'other', label: 'Sonstiges' },
  ],
  communicationStatuses: [
    { id: 'PENDING', label: 'Wartend' },
    { id: 'COMPLETED', label: 'Abgeschlossen' },
    { id: 'CANCELLED', label: 'Abgebrochen' },
    { id: 'SCHEDULED', label: 'Geplant' },
  ],
  jobStatuses: [
    { id: 'OPEN', label: 'Offen' },
    { id: 'IN_PROGRESS', label: 'In Bearbeitung' },
    { id: 'CLOSED', label: 'Geschlossen' },
    { id: 'REJECTED', label: 'Abgelehnt' },
    { id: 'ACCEPTED', label: 'Angenommen' },
  ],
});
